### ISSUE TITLE
Scroll Horizontal sur Firefox

### ISSUE THREAD

**Issue by oriionn** [PapillonApp/papillon.bzh-v7#1]
Il y a un scroll horizontal sur Firefox ESR

![2024-08-28_19_43_44](https://github.com/user-attachments/assets/6f683cfd-7fbf-49da-9bba-5f18011a2a06)

**Comment by ecnivtwelve** [comment]
Est-ce-que cela fix le problème : https://github.com/PapillonApp/papillon.bzh/commit/3edf0498afb842b14d163bc2271ac9fe5dea412d

**Comment by oriionn** [comment]
> Est-ce-que cela fix le problème : [3edf049](https://github.com/PapillonApp/papillon.bzh/commit/3edf0498afb842b14d163bc2271ac9fe5dea412d)

Je te dis ça dès que ça se deploy

**Comment by Rexxt** [comment]
> Est-ce-que cela fix le problème : [3edf049](https://github.com/PapillonApp/papillon.bzh/commit/3edf0498afb842b14d163bc2271ac9fe5dea412d)

erreur dans la propriété (`overflox-x`)

**Comment by oriionn** [comment]
Ça marche ! (Comme dirait Pécresse)

![2024-08-28_19_50_36](https://github.com/user-attachments/assets/61d3da64-b631-4a40-bd7f-b94e999939a1)

**Comment by oriionn** [comment]
> > Est-ce-que cela fix le problème : [3edf049](https://github.com/PapillonApp/papillon.bzh/commit/3edf0498afb842b14d163bc2271ac9fe5dea412d)
> 
> erreur dans la propriété (`overflox-x`)

Déjà prévenu, pas la peine de lui foutre la honte en public 😆
![image](https://github.com/user-attachments/assets/a5b4a694-a313-4e90-aa2e-63370f7e06cf)

**Comment by Rexxt** [comment]
je pref lui foutre la honte c'est plus drôle
