### ISSUE TITLE
[Enhancement]: Ajouter un embed à la page de donation

### ISSUE THREAD

**Issue by oriionn** [PapillonApp/papillon.bzh-v7#2]
### Description du problème

Quand on partage le lien pour la donation sur Discord par exemple, un embed ne s'affiche pas.
![image](https://github.com/user-attachments/assets/312ceb15-c66a-442e-a4f3-b1153518ef38)

### Description de l'amélioration

Ajouter un embed comme pour la page d'accueil, ce qui donnera encore plus envie aux gens de donner de l'argent à Papillon 😎
![image](https://github.com/user-attachments/assets/784adb16-3a20-4c49-882e-3e4dfbaf7c11)

**Comment by ecnivtwelve** [comment]
Normalement ajouté ici -> https://github.com/PapillonApp/papillon.bzh/commit/ea7b0ad4be950fd9b2d294aa8fedac5f62bf3d0f

**Comment by ecnivtwelve** [comment]
Pour une raison que j'ignore (surement liée au SSG) l'embed marche pas (il devrait en avoir un)

**Comment by oriionn** [comment]
> Pour une raison que j'ignore (surement liée au SSG) l'embed marche pas (il devrait en avoir un)

Certainement le cache de Discord aussi TT

**Comment by oriionn** [comment]
![image](https://github.com/user-attachments/assets/42881884-ff4a-4cef-88f9-b5d6b7f7b769)
C'est bon !
